services:
  - type: web
    name: testlink-app
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.php
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testlink-db
          property: connectionString

databases:
  - name: testlink-db
    databaseName: testlink
    user: testlink_user
    region: oregon
    plan: free
